# Change these first
owner: Blip-Core # Your GitHub organization or username, where this repository lives
repo: bliphq-status # The name of this repository

sites:
  - name: Home
    url: https://bliphq.org
    icon: https://bliphq.org/assets/favicon.svg
  - name: Bezel
    url: https://bezel.bliphq.org
    icon: https://bliphq.org/assets/favicon.svg
  - name: Status
    url: https://status.bliphq.org
    icon: https://bliphq.org/assets/status/normal.svg

status-website:
  cname: status.bliphq.org
  # baseUrl: /bliphq-status # Add your repo slug here so relative paths resolve cleanly
  # baseUrl: /bliphq-status
  logoUrl: https://bliphq.org/assets/favicon.svg
  name: Blip Status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

  customFootHtml: |
    <script>function updateFavicon() {
      const isDown = document.querySelector('.down-active') !== null;
      const isDegraded = document.querySelector('.degraded') !== null;
      let link = document.querySelector("link[rel*='icon']") || document.createElement('link'); link.type = 'image/x-icon';
      link.rel = 'shortcut icon'; link.href = isDown ? 'https://bliphq.org/assets/status/down.svg' : isDegraded ? 'https://bliphq.org/assets/status/degraded.svg' : 'https://bliphq.org/assets/status/normal.svg';
      document.head.appendChild(link);
    }

    // Run immediately when injected
    updateFavicon();
    
    // Check every 2 seconds to catch Upptime's async Svelte elements when they render
    setInterval(updateFavicon, 2000);</script>
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
